version: "3"

services:
  web:
    build: .
    # Agora usando Uvicorn para rodar o ASGI (Channels)
    command: >
      uvicorn config.asgi:application
      --host 0.0.0.0 --port 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    command: celery -A config worker --loglevel=info --without-gossip --without-mingle --without-heartbeat --max-tasks-per-child=100
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    container_name: redis_mxrouter
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles:ro
      - media_volume:/home/app/web/mediafiles:ro
    ports:
      - 1337:80


volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis:
