# Generated by Django 5.2 on 2025-05-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='document',
            field=models.ManyToManyField(blank=True, help_text='Documentos relacionados ao motorista', related_name='documents_drive', to='tmsapp.document', verbose_name='Documentos'),
        ),
    ]
