# Generated by Django 5.2 on 2025-05-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicle',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano de Fabricação'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano de Fabricação'),
        ),
    ]
