# Generated by Django 5.2 on 2025-05-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0002_alter_historicalvehicle_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicle',
            name='capacity_volume',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Capacidade (m³)'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='capacity_weight',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Capacidade (kg)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity_volume',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Capacidade (m³)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity_weight',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Capacidade (kg)'),
        ),
    ]
