# Generated by Django 5.2 on 2025-05-23 12:02

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0002_alter_driver_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLoadPlan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nome do Plano')),
                ('planned_date', models.DateField(blank=True, db_index=True, editable=False, verbose_name='Data Planejada')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Horário de Saída')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('planned', 'Planejado'), ('loading', 'Carregando'), ('departed', 'Saiu para Entrega'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], db_index=True, default='completed', max_length=20, verbose_name='Status')),
                ('max_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Capacidade Peso (kg)')),
                ('max_volume_m3', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Capacidade Volume (m³)')),
                ('total_deliveries', models.PositiveIntegerField(default=0, editable=False, verbose_name='Total de Entregas')),
                ('total_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=12, verbose_name='Peso Total (kg)')),
                ('total_volume_m3', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=12, verbose_name='Volume Total (m³)')),
                ('weight_utilization_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5, verbose_name='Utilização Peso (%)')),
                ('volume_utilization_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5, verbose_name='Utilização Volume (%)')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Plano de Carga',
                'verbose_name_plural': 'historical Planos de Carga',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LoadPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nome do Plano')),
                ('planned_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Data Planejada')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Horário de Saída')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('planned', 'Planejado'), ('loading', 'Carregando'), ('departed', 'Saiu para Entrega'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], db_index=True, default='completed', max_length=20, verbose_name='Status')),
                ('max_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Capacidade Peso (kg)')),
                ('max_volume_m3', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Capacidade Volume (m³)')),
                ('total_deliveries', models.PositiveIntegerField(default=0, editable=False, verbose_name='Total de Entregas')),
                ('total_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=12, verbose_name='Peso Total (kg)')),
                ('total_volume_m3', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=12, verbose_name='Volume Total (m³)')),
                ('weight_utilization_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5, verbose_name='Utilização Peso (%)')),
                ('volume_utilization_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5, verbose_name='Utilização Volume (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano de Carga',
                'verbose_name_plural': 'Planos de Carga',
                'ordering': ['-planned_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteCompositionDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='Sequência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entrega da Composição de Rota',
                'verbose_name_plural': 'Entregas da Composição de Rota',
                'ordering': ['sequence'],
            },
        ),
        migrations.RemoveField(
            model_name='historicalload',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalload',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='historicalload',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalload',
            name='route',
        ),
        migrations.RemoveField(
            model_name='historicalload',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='historicalloaddelivery',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='historicalloaddelivery',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalloaddelivery',
            name='load',
        ),
        migrations.RemoveField(
            model_name='load',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='load',
            name='deliveries',
        ),
        migrations.RemoveField(
            model_name='load',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='load',
            name='route',
        ),
        migrations.RemoveField(
            model_name='load',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='loaddelivery',
            name='load',
        ),
        migrations.AlterUniqueTogether(
            name='loaddelivery',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='loaddelivery',
            name='delivery',
        ),
        migrations.AlterModelOptions(
            name='historicalroutecomposition',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Roterização', 'verbose_name_plural': 'historical Roterizações'},
        ),
        migrations.AlterModelOptions(
            name='routecomposition',
            options={'verbose_name': 'Roterização', 'verbose_name_plural': 'Roterizações'},
        ),
        migrations.RemoveField(
            model_name='historicalroutecomposition',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='historicalroutecomposition',
            name='type',
        ),
        migrations.RemoveField(
            model_name='routecomposition',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='routecomposition',
            name='routes',
        ),
        migrations.RemoveField(
            model_name='routecomposition',
            name='type',
        ),
        migrations.AddField(
            model_name='companylocation',
            name='closing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Fechamento'),
        ),
        migrations.AddField(
            model_name='companylocation',
            name='code',
            field=models.CharField(blank=True, help_text='Código único do local (ex: ARM001, LOJA-SP)', max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='companylocation',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='companylocation',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='companylocation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='companylocation',
            name='is_departure_point',
            field=models.BooleanField(default=False, help_text='Indica se este local pode ser usado como ponto de partida para entregas', verbose_name='Ponto de Saída'),
        ),
        migrations.AddField(
            model_name='companylocation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='companylocation',
            name='opening_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Abertura'),
        ),
        migrations.AddField(
            model_name='companylocation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='capacity_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Capacidade (m³)'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='capacity_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Capacidade (kg)'),
        ),
        migrations.AddField(
            model_name='historicalcompanylocation',
            name='closing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Fechamento'),
        ),
        migrations.AddField(
            model_name='historicalcompanylocation',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Código único do local (ex: ARM001, LOJA-SP)', max_length=20, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='historicalcompanylocation',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='historicalcompanylocation',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='historicalcompanylocation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='historicalcompanylocation',
            name='is_departure_point',
            field=models.BooleanField(default=False, help_text='Indica se este local pode ser usado como ponto de partida para entregas', verbose_name='Ponto de Saída'),
        ),
        migrations.AddField(
            model_name='historicalcompanylocation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='historicalcompanylocation',
            name='opening_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Abertura'),
        ),
        migrations.AddField(
            model_name='historicalcompanylocation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='capacity_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Capacidade (m³)'),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='capacity_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Capacidade (kg)'),
        ),
        migrations.AddField(
            model_name='historicalroute',
            name='route_area',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmsapp.routearea', verbose_name='Área de Rota'),
        ),
        migrations.AddField(
            model_name='historicalroutearea',
            name='departure_location',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Local de partida padrão para rotas desta área', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmsapp.companylocation', verbose_name='Ponto de Saída'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='tmsapp.routearea', verbose_name='Área de Rota'),
        ),
        migrations.AddField(
            model_name='routearea',
            name='departure_location',
            field=models.ForeignKey(blank=True, help_text='Local de partida padrão para rotas desta área', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_areas_departure', to='tmsapp.companylocation', verbose_name='Ponto de Saída'),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='city',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='is_principal',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Principal'),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='state',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='type',
            field=models.CharField(choices=[('warehouse', 'Armazém'), ('store', 'Loja'), ('distribution_center', 'Centro de Distribuição'), ('hub', 'Hub'), ('departure_point', 'Ponto de Saída'), ('secondary_warehouse', 'Armazém Secundário'), ('other', 'Outro')], db_index=True, default='other', max_length=30, verbose_name='Tipo de Local'),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='zip_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='historicalcompanylocation',
            name='city',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='historicalcompanylocation',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='historicalcompanylocation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='historicalcompanylocation',
            name='is_principal',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Principal'),
        ),
        migrations.AlterField(
            model_name='historicalcompanylocation',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='historicalcompanylocation',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='historicalcompanylocation',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalcompanylocation',
            name='state',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalcompanylocation',
            name='type',
            field=models.CharField(choices=[('warehouse', 'Armazém'), ('store', 'Loja'), ('distribution_center', 'Centro de Distribuição'), ('hub', 'Hub'), ('departure_point', 'Ponto de Saída'), ('secondary_warehouse', 'Armazém Secundário'), ('other', 'Outro')], db_index=True, default='other', max_length=30, verbose_name='Tipo de Local'),
        ),
        migrations.AlterField(
            model_name='historicalcompanylocation',
            name='zip_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalroutearea',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalroutearea',
            name='geojson',
            field=models.TextField(blank=True, default=dict, help_text='Texto JSON bruto do polígono da área', null=True, verbose_name='GeoJSON'),
        ),
        migrations.AlterField(
            model_name='historicalroutearea',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='historicalroutearea',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalroutearea',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('disabled', 'Desabilitado')], db_index=True, default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroutecomposition',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalroutecomposition',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='historicalroutecomposition',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='capacity_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Capacidade (m³)'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='capacity_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Capacidade (kg)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='geojson',
            field=models.TextField(blank=True, default=dict, help_text='Texto JSON bruto do polígono da área', null=True, verbose_name='GeoJSON'),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('disabled', 'Desabilitado')], db_index=True, default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='routecomposition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='routecomposition',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='routecomposition',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Capacidade (m³)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Capacidade (kg)'),
        ),
        migrations.AddIndex(
            model_name='companylocation',
            index=models.Index(fields=['is_active', 'type'], name='tmsapp_comp_is_acti_85209c_idx'),
        ),
        migrations.AddIndex(
            model_name='companylocation',
            index=models.Index(fields=['is_principal', 'is_active'], name='tmsapp_comp_is_prin_196c54_idx'),
        ),
        migrations.AddIndex(
            model_name='companylocation',
            index=models.Index(fields=['is_departure_point', 'is_active'], name='tmsapp_comp_is_depa_6864e6_idx'),
        ),
        migrations.AddIndex(
            model_name='companylocation',
            index=models.Index(fields=['city', 'state'], name='tmsapp_comp_city_997aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='companylocation',
            index=models.Index(fields=['latitude', 'longitude'], name='tmsapp_comp_latitud_7dbe2a_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['-created_at', 'is_active'], name='tmsapp_rout_created_848759_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['route_area', 'is_active'], name='tmsapp_rout_route_a_2eff5b_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['distance_km', 'time_min'], name='tmsapp_rout_distanc_18e79b_idx'),
        ),
        migrations.AddIndex(
            model_name='routearea',
            index=models.Index(fields=['is_active', 'status'], name='tmsapp_rout_is_acti_8a1b28_idx'),
        ),
        migrations.AddIndex(
            model_name='routearea',
            index=models.Index(fields=['-created_at', 'is_active'], name='tmsapp_rout_created_05e7e0_idx'),
        ),
        migrations.AddIndex(
            model_name='routearea',
            index=models.Index(fields=['departure_location', 'is_active'], name='tmsapp_rout_departu_17927f_idx'),
        ),
        migrations.AddIndex(
            model_name='routedelivery',
            index=models.Index(fields=['route', 'position'], name='tmsapp_rout_route_i_641b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='routedelivery',
            index=models.Index(fields=['delivery', 'route'], name='tmsapp_rout_deliver_ad1563_idx'),
        ),
        migrations.AddField(
            model_name='historicalloadplan',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalloadplan',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalloadplan',
            name='route',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmsapp.route', verbose_name='Rota'),
        ),
        migrations.AddField(
            model_name='historicalloadplan',
            name='vehicle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmsapp.vehicle', verbose_name='Veículo'),
        ),
        migrations.AddField(
            model_name='loadplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_plans_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loadplan',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmsapp.route', verbose_name='Rota'),
        ),
        migrations.AddField(
            model_name='loadplan',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmsapp.vehicle', verbose_name='Veículo'),
        ),
        migrations.AddField(
            model_name='routecompositiondelivery',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition_assignments', to='tmsapp.delivery'),
        ),
        migrations.AddField(
            model_name='routecompositiondelivery',
            name='load_plan',
            field=models.ForeignKey(blank=True, help_text='Plano de carga ao qual este pedido pertence. Null para pedidos fora de carga.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmsapp.loadplan', verbose_name='Plano de Carga'),
        ),
        migrations.AddField(
            model_name='routecompositiondelivery',
            name='route_composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition_deliveries', to='tmsapp.routecomposition'),
        ),
        migrations.AddField(
            model_name='routecomposition',
            name='deliveries',
            field=models.ManyToManyField(related_name='route_compositions', through='tmsapp.RouteCompositionDelivery', to='tmsapp.delivery', verbose_name='Entregas'),
        ),
        migrations.AddIndex(
            model_name='routecomposition',
            index=models.Index(fields=['-created_at', 'is_active'], name='tmsapp_rout_created_1b03e5_idx'),
        ),
        migrations.DeleteModel(
            name='HistoricalLoad',
        ),
        migrations.DeleteModel(
            name='HistoricalLoadDelivery',
        ),
        migrations.DeleteModel(
            name='Load',
        ),
        migrations.DeleteModel(
            name='LoadDelivery',
        ),
        migrations.AddIndex(
            model_name='loadplan',
            index=models.Index(fields=['-planned_date', 'status'], name='tmsapp_load_planned_3233df_idx'),
        ),
        migrations.AddIndex(
            model_name='loadplan',
            index=models.Index(fields=['vehicle', 'status'], name='tmsapp_load_vehicle_c79875_idx'),
        ),
        migrations.AddIndex(
            model_name='loadplan',
            index=models.Index(fields=['route', 'planned_date'], name='tmsapp_load_route_i_9f8d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='routecompositiondelivery',
            index=models.Index(fields=['route_composition', 'sequence'], name='tmsapp_rout_route_c_6fb808_idx'),
        ),
        migrations.AddIndex(
            model_name='routecompositiondelivery',
            index=models.Index(fields=['load_plan', 'delivery'], name='tmsapp_rout_load_pl_92bde9_idx'),
        ),
        migrations.AddIndex(
            model_name='routecompositiondelivery',
            index=models.Index(fields=['delivery', 'load_plan'], name='tmsapp_rout_deliver_dc7ff8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routecompositiondelivery',
            unique_together={('route_composition', 'delivery')},
        ),
    ]
