# Generated by Django 5.2 on 2025-05-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0003_alter_historicalvehicle_capacity_volume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='capacity_volume',
            new_name='total_volume_m3',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='capacity_weight',
            new_name='total_weight_kg',
        ),
        migrations.RenameField(
            model_name='historicaldelivery',
            old_name='capacity_volume',
            new_name='total_volume_m3',
        ),
        migrations.RenameField(
            model_name='historicaldelivery',
            old_name='capacity_weight',
            new_name='total_weight_kg',
        ),
        migrations.RenameField(
            model_name='historicalvehicle',
            old_name='capacity_weight',
            new_name='max_volume_kg',
        ),
        migrations.RenameField(
            model_name='historicalvehicle',
            old_name='capacity_volume',
            new_name='max_volume_m3',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='capacity_weight',
            new_name='max_volume_kg',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='capacity_volume',
            new_name='max_volume_m3',
        ),
    ]
