# Generated by Django 5.2 on 2025-05-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0004_rename_capacity_volume_delivery_total_volume_m3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvehicle',
            old_name='max_volume_kg',
            new_name='max_weight_kg',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='max_volume_kg',
            new_name='max_weight_kg',
        ),
    ]
