# Generated by Django 5.2 on 2025-05-09 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0004_alter_historicalroutearea_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalroutearea',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Área de Rota', 'verbose_name_plural': 'historical Áreas de Rotas'},
        ),
        migrations.AlterModelOptions(
            name='historicalroutecomposition',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Composição de Rota', 'verbose_name_plural': 'historical Composições de Rotas'},
        ),
        migrations.AlterModelOptions(
            name='routearea',
            options={'verbose_name': 'Área de Rota', 'verbose_name_plural': 'Áreas de Rotas'},
        ),
        migrations.AlterModelOptions(
            name='routecomposition',
            options={'verbose_name': 'Composição de Rota', 'verbose_name_plural': 'Composições de Rotas'},
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='address',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='route_name',
        ),
        migrations.RemoveField(
            model_name='historicaldelivery',
            name='address',
        ),
        migrations.RemoveField(
            model_name='historicaldelivery',
            name='route_name',
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='number',
            field=models.CharField(default='0', max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='Marcado no Mapa'),
        ),
        migrations.AlterField(
            model_name='historicalcompanylocation',
            name='number',
            field=models.CharField(default='0', max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='historicaldelivery',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='Marcado no Mapa'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='color',
            field=models.CharField(default='#3498db', max_length=7, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='distance_km',
            field=models.FloatField(verbose_name='Distância (km)'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='stops',
            field=models.PositiveIntegerField(verbose_name='Paradas'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='time_min',
            field=models.FloatField(verbose_name='Tempo (minutos)'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='historicalroutearea',
            name='areatotal',
            field=models.FloatField(blank=True, null=True, verbose_name='Área Total (m²)'),
        ),
        migrations.AlterField(
            model_name='historicalroutearea',
            name='cep_end',
            field=models.JSONField(blank=True, default=list, verbose_name='CEP Fim'),
        ),
        migrations.AlterField(
            model_name='historicalroutearea',
            name='cep_start',
            field=models.JSONField(blank=True, default=list, verbose_name='CEP Início'),
        ),
        migrations.AlterField(
            model_name='historicalroutearea',
            name='cities',
            field=models.JSONField(blank=True, default=list, verbose_name='Cidades'),
        ),
        migrations.AlterField(
            model_name='historicalroutearea',
            name='color_name',
            field=models.CharField(choices=[('orange', 'Laranja'), ('green', 'Verde'), ('blue', 'Azul'), ('purple', 'Roxo'), ('darkred', 'Vermelho Escuro'), ('darkgreen', 'Verde Escuro'), ('darkblue', 'Azul Escuro'), ('cadetblue', 'Azul Cadete'), ('lightred', 'Vermelho Claro'), ('beige', 'Bege'), ('lightgreen', 'Verde Claro'), ('lightblue', 'Azul Claro'), ('darkpurple', 'Roxo Escuro'), ('pink', 'Rosa'), ('gray', 'Cinza')], default='blue', max_length=20, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='historicalroutearea',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='historicalroutearea',
            name='geojson',
            field=models.TextField(default=dict, help_text='Texto JSON bruto; será convertido depois', verbose_name='GeoJSON'),
        ),
        migrations.AlterField(
            model_name='historicalroutearea',
            name='kmtotal',
            field=models.FloatField(blank=True, null=True, verbose_name='Distância Total (km)'),
        ),
        migrations.AlterField(
            model_name='historicalroutearea',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalroutearea',
            name='neighborhoods',
            field=models.JSONField(blank=True, default=list, verbose_name='Bairros'),
        ),
        migrations.AlterField(
            model_name='historicalroutearea',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('disabled', 'Desabilitado')], default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroutearea',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalroutecomposition',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalroutecomposition',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='historicalroutecomposition',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalroutecomposition',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='historicalroutecomposition',
            name='type',
            field=models.CharField(choices=[('city', 'Rotas por cidade'), ('unique', 'Rota única'), ('custom', 'Rota Personalizada'), ('other', 'Outro')], default='other', max_length=30, verbose_name='Tipo de Rota'),
        ),
        migrations.AlterField(
            model_name='historicalroutecomposition',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalroutedelivery',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalroutedelivery',
            name='position',
            field=models.PositiveIntegerField(verbose_name='Posição na Rota'),
        ),
        migrations.AlterField(
            model_name='historicalroutedelivery',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='color',
            field=models.CharField(default='#3498db', max_length=7, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='route',
            name='deliveries',
            field=models.ManyToManyField(related_name='routes', through='tmsapp.RouteDelivery', to='tmsapp.delivery', verbose_name='Entregas'),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance_km',
            field=models.FloatField(verbose_name='Distância (km)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stops',
            field=models.PositiveIntegerField(verbose_name='Paradas'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_min',
            field=models.FloatField(verbose_name='Tempo (minutos)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='areatotal',
            field=models.FloatField(blank=True, null=True, verbose_name='Área Total (m²)'),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='cep_end',
            field=models.JSONField(blank=True, default=list, verbose_name='CEP Fim'),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='cep_start',
            field=models.JSONField(blank=True, default=list, verbose_name='CEP Início'),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='cities',
            field=models.JSONField(blank=True, default=list, verbose_name='Cidades'),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='color_name',
            field=models.CharField(choices=[('orange', 'Laranja'), ('green', 'Verde'), ('blue', 'Azul'), ('purple', 'Roxo'), ('darkred', 'Vermelho Escuro'), ('darkgreen', 'Verde Escuro'), ('darkblue', 'Azul Escuro'), ('cadetblue', 'Azul Cadete'), ('lightred', 'Vermelho Claro'), ('beige', 'Bege'), ('lightgreen', 'Verde Claro'), ('lightblue', 'Azul Claro'), ('darkpurple', 'Roxo Escuro'), ('pink', 'Rosa'), ('gray', 'Cinza')], default='blue', max_length=20, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_areas_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='geojson',
            field=models.TextField(default=dict, help_text='Texto JSON bruto; será convertido depois', verbose_name='GeoJSON'),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='kmtotal',
            field=models.FloatField(blank=True, null=True, verbose_name='Distância Total (km)'),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='neighborhoods',
            field=models.JSONField(blank=True, default=list, verbose_name='Bairros'),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('disabled', 'Desabilitado')], default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='routecomposition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='routecomposition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_compositions_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='routecomposition',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='routecomposition',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='routecomposition',
            name='routes',
            field=models.ManyToManyField(related_name='compositions', to='tmsapp.route', verbose_name='Rotas'),
        ),
        migrations.AlterField(
            model_name='routecomposition',
            name='type',
            field=models.CharField(choices=[('city', 'Rotas por cidade'), ('unique', 'Rota única'), ('custom', 'Rota Personalizada'), ('other', 'Outro')], default='other', max_length=30, verbose_name='Tipo de Rota'),
        ),
        migrations.AlterField(
            model_name='routecomposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='routedelivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='routedelivery',
            name='position',
            field=models.PositiveIntegerField(verbose_name='Posição na Rota'),
        ),
        migrations.AlterField(
            model_name='routedelivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='routearea',
            table=None,
        ),
    ]
