# Generated by Django 5.2 on 2025-05-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0005_rename_max_volume_kg_historicalvehicle_max_weight_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalroutecomposition',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('completed', 'Completa'), ('cancelled', 'Cancelada')], db_index=True, default='draft', help_text='Situação atual da roterização', max_length=15, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='routecomposition',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('completed', 'Completa'), ('cancelled', 'Cancelada')], db_index=True, default='draft', help_text='Situação atual da roterização', max_length=15, verbose_name='Status'),
        ),
    ]
