# Generated by Django 5.2 on 2025-05-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0006_driver_historicaldriver_historicalvehicle_load_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicle',
            name='profile',
            field=models.CharField(choices=[('driving-car', 'Carro'), ('driving-hgv', 'Caminhão/Veículo pesado')], default='driving-car', help_text='Modo de roteirização conforme ORS', max_length=20, verbose_name='Perfil ORS'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='profile',
            field=models.CharField(choices=[('driving-car', 'Carro'), ('driving-hgv', 'Caminhão/Veículo pesado')], default='driving-car', help_text='Modo de roteirização conforme ORS', max_length=20, verbose_name='Perfil ORS'),
        ),
    ]
