# Generated by Django 5.2 on 2025-05-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0006_historicalroutecomposition_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'pendente'), ('in-load', 'em carga'), ('in-transit', 'em Trânsito'), ('delivered', 'entregue'), ('failed', 'falha na Entrega'), ('cancelled', 'cancelada')], db_index=True, default='pending', help_text='Situação atual da entrega', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicaldelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'pendente'), ('in-load', 'em carga'), ('in-transit', 'em Trânsito'), ('delivered', 'entregue'), ('failed', 'falha na Entrega'), ('cancelled', 'cancelada')], db_index=True, default='pending', help_text='Situação atual da entrega', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalloadplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('planned', 'Planejado'), ('loading', 'Carregando'), ('departed', 'Saiu para Entrega'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroutecomposition',
            name='status',
            field=models.CharField(choices=[('draft', 'rascunho'), ('completed', 'completa'), ('cancelled', 'cancelada')], db_index=True, default='draft', help_text='Situação atual da roterização', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='loadplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('planned', 'Planejado'), ('loading', 'Carregando'), ('departed', 'Saiu para Entrega'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='routecomposition',
            name='status',
            field=models.CharField(choices=[('draft', 'rascunho'), ('completed', 'completa'), ('cancelled', 'cancelada')], db_index=True, default='draft', help_text='Situação atual da roterização', max_length=15, verbose_name='Status'),
        ),
    ]
