# Generated by Django 5.2 on 2025-05-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0007_alter_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor da nota'),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor da nota'),
        ),
    ]
