# Generated by Django 5.2 on 2025-05-09 22:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0007_alter_historicalvehicle_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='aggregated_vehicles',
        ),
        migrations.AddField(
            model_name='driver',
            name='is_outsourced',
            field=models.BooleanField(default=False, verbose_name='Terceirizado'),
        ),
        migrations.AddField(
            model_name='historicaldriver',
            name='is_outsourced',
            field=models.BooleanField(default=False, verbose_name='Terceirizado'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='driver',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmsapp.driver', verbose_name='Motorista Interno'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='is_outsourced',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, utilizar transportadora em vez de motorista interno', verbose_name='Terceirizado'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='tmsapp.driver', verbose_name='Motorista Interno'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_outsourced',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, utilizar transportadora em vez de motorista interno', verbose_name='Terceirizado'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Conta de usuário associada ao motorista', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='profile',
            field=models.CharField(choices=[('driving-car', 'Carro'), ('driving-hgv', 'Caminhão/Veículo pesado')], default='driving-hgv', help_text='Modo de roteirização conforme ORS', max_length=20, verbose_name='Perfil ORS'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='profile',
            field=models.CharField(choices=[('driving-car', 'Carro'), ('driving-hgv', 'Caminhão/Veículo pesado')], default='driving-hgv', help_text='Modo de roteirização conforme ORS', max_length=20, verbose_name='Perfil ORS'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Transportadora')),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carriers_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Transportadora',
                'verbose_name_plural': 'Transportadoras',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='carrier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmsapp.carrier', verbose_name='Transportadora'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='tmsapp.carrier', verbose_name='Transportadora'),
        ),
        migrations.CreateModel(
            name='HistoricalCarrier',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Transportadora')),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Transportadora',
                'verbose_name_plural': 'historical Transportadoras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
