# Generated by Django 5.2 on 2025-05-09 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0008_remove_vehicle_aggregated_vehicles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='representative',
            field=models.ForeignKey(blank=True, help_text='Motorista ou representante interno da transportadora', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carriers_represented', to='tmsapp.driver', verbose_name='Representante/Motorista'),
        ),
        migrations.AddField(
            model_name='historicalcarrier',
            name='representative',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Motorista ou representante interno da transportadora', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmsapp.driver', verbose_name='Representante/Motorista'),
        ),
    ]
