# Generated by Django 5.2 on 2025-05-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0008_delivery_price_historicaldelivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalloadplan',
            name='total_volume_m3',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Volume Total (m³)'),
        ),
        migrations.AlterField(
            model_name='historicalloadplan',
            name='total_weight_kg',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Peso Total (kg)'),
        ),
        migrations.AlterField(
            model_name='historicalloadplan',
            name='volume_utilization_pct',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Utilização Volume (%)'),
        ),
        migrations.AlterField(
            model_name='historicalloadplan',
            name='weight_utilization_pct',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Utilização Peso (%)'),
        ),
        migrations.AlterField(
            model_name='loadplan',
            name='total_volume_m3',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Volume Total (m³)'),
        ),
        migrations.AlterField(
            model_name='loadplan',
            name='total_weight_kg',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Peso Total (kg)'),
        ),
        migrations.AlterField(
            model_name='loadplan',
            name='volume_utilization_pct',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Utilização Volume (%)'),
        ),
        migrations.AlterField(
            model_name='loadplan',
            name='weight_utilization_pct',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Utilização Peso (%)'),
        ),
    ]
