# Generated by Django 5.2 on 2025-05-09 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0009_carrier_representative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fim')),
            ],
            options={
                'verbose_name': 'Atribuição de Veículo',
                'verbose_name_plural': 'Atribuições de Veículo',
                'ordering': ['-start_date'],
            },
        ),
        migrations.RemoveField(
            model_name='historicalvehicle',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='profile',
        ),
        migrations.AlterField(
            model_name='carrier',
            name='contact_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nome da Transportadora'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='representative',
            field=models.ForeignKey(blank=True, help_text='Motorista ou representante interno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carriers_represented', to='tmsapp.driver', verbose_name='Representante/Motorista'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='CNH'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcarrier',
            name='contact_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='historicalcarrier',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='historicalcarrier',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nome da Transportadora'),
        ),
        migrations.AlterField(
            model_name='historicalcarrier',
            name='representative',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Motorista ou representante interno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmsapp.driver', verbose_name='Representante/Motorista'),
        ),
        migrations.AlterField(
            model_name='historicaldriver',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicaldriver',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaldriver',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='historicaldriver',
            name='license_number',
            field=models.CharField(db_index=True, max_length=20, verbose_name='CNH'),
        ),
        migrations.AlterField(
            model_name='historicaldriver',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='historicaldriver',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicaldriver',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='is_outsourced',
            field=models.BooleanField(default=False, verbose_name='Terceirizado'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('maintenance', 'Em manutenção'), ('decommissioned', 'Baixado')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_outsourced',
            field=models.BooleanField(default=False, verbose_name='Terceirizado'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('maintenance', 'Em manutenção'), ('decommissioned', 'Baixado')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['name'], name='tmsapp_carr_name_567441_idx'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['contact_name'], name='tmsapp_carr_contact_ddced1_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['license_number'], name='tmsapp_driv_license_007932_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['email'], name='tmsapp_driv_email_9a510e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['license_plate'], name='tmsapp_vehi_license_eac79a_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['brand', 'model'], name='tmsapp_vehi_brand_fa22e4_idx'),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='tmsapp.driver'),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tmsapp.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleassignment',
            unique_together={('vehicle', 'driver', 'start_date')},
        ),
    ]
