# Generated by Django 5.2 on 2025-05-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0009_alter_historicalloadplan_total_volume_m3_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routecompositiondelivery',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='routecompositiondelivery',
            constraint=models.UniqueConstraint(fields=('delivery',), name='unique_delivery_global'),
        ),
    ]
