# Generated by Django 5.2 on 2025-05-09 23:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0010_vehicleassignment_remove_historicalvehicle_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Documento')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Arquivo')),
                ('issued_date', models.DateField(verbose_name='Data de Emissão')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='document_photos/%Y/%m/', verbose_name='Foto do Documento')),
                ('caption', models.CharField(blank=True, help_text='Descrição opcional da foto', max_length=255, null=True, verbose_name='Legenda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto de Documento',
                'verbose_name_plural': 'Fotos de Documento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='carrier',
            name='document',
            field=models.ManyToManyField(blank=True, help_text='Documentos relacionados a transportadora', related_name='documents_carrier', to='tmsapp.document', verbose_name='Documentos'),
        ),
        migrations.AddField(
            model_name='driver',
            name='document',
            field=models.ManyToManyField(blank=True, help_text='Documentos relacionados ao motorista', related_name='documents_drive', to='tmsapp.document', verbose_name='Documentos'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='document',
            field=models.ManyToManyField(blank=True, help_text='Documentos relacionados ao veículo', related_name='documents_vehicles', to='tmsapp.document', verbose_name='Documentos'),
        ),
        migrations.AddField(
            model_name='document',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='documents', to='tmsapp.documentphoto', verbose_name='Fotos do Documento'),
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Inspeção')),
                ('status', models.BooleanField(default=True, verbose_name='Aprovado')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_created', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='tmsapp.vehicle')),
            ],
            options={
                'verbose_name': 'Inspeção',
                'verbose_name_plural': 'Inspeções',
                'ordering': ['-date'],
            },
        ),
    ]
