# Generated by Django 5.2 on 2025-05-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0010_alter_routecompositiondelivery_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='total_volume_m3',
            field=models.FloatField(default=0.0, help_text='Volume em m³', verbose_name='Capacidade (m³)'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='total_weight_kg',
            field=models.FloatField(default=0.0, help_text='Peso em kg', verbose_name='Capacidade (kg)'),
        ),
        migrations.AlterField(
            model_name='historicaldelivery',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='historicaldelivery',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='historicaldelivery',
            name='total_volume_m3',
            field=models.FloatField(default=0.0, help_text='Volume em m³', verbose_name='Capacidade (m³)'),
        ),
        migrations.AlterField(
            model_name='historicaldelivery',
            name='total_weight_kg',
            field=models.FloatField(default=0.0, help_text='Peso em kg', verbose_name='Capacidade (kg)'),
        ),
    ]
