# Generated by Django 5.2 on 2025-05-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0011_document_documentphoto_carrier_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalroutearea',
            name='geojson',
            field=models.TextField(blank=True, default=dict, help_text='Texto JSON bruto; será convertido depois', null=True, verbose_name='GeoJSON'),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='geojson',
            field=models.TextField(blank=True, default=dict, help_text='Texto JSON bruto; será convertido depois', null=True, verbose_name='GeoJSON'),
        ),
    ]
