# Generated by Django 5.2 on 2025-05-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0012_alter_delivery_latitude_alter_delivery_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalloadplan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalloadplan',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalloadplan',
            name='route',
        ),
        migrations.RemoveField(
            model_name='historicalloadplan',
            name='vehicle',
        ),
        migrations.RemoveIndex(
            model_name='loadplan',
            name='tmsapp_load_planned_3233df_idx',
        ),
        migrations.RemoveIndex(
            model_name='loadplan',
            name='tmsapp_load_vehicle_c79875_idx',
        ),
        migrations.RemoveIndex(
            model_name='loadplan',
            name='tmsapp_load_route_i_9f8d3e_idx',
        ),
        migrations.RemoveField(
            model_name='loadplan',
            name='total_deliveries',
        ),
        migrations.RemoveField(
            model_name='loadplan',
            name='total_volume_m3',
        ),
        migrations.RemoveField(
            model_name='loadplan',
            name='total_weight_kg',
        ),
        migrations.RemoveField(
            model_name='loadplan',
            name='volume_utilization_pct',
        ),
        migrations.RemoveField(
            model_name='loadplan',
            name='weight_utilization_pct',
        ),
        migrations.AlterField(
            model_name='routecompositiondelivery',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='HistoricalLoadPlan',
        ),
    ]
