# Generated by Django 5.2 on 2025-05-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0012_alter_historicalroutearea_geojson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='document',
            field=models.ManyToManyField(blank=True, help_text='Documentos relacionados ao motorista', null=True, related_name='documents_drive', to='tmsapp.document', verbose_name='Documentos'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_category',
            field=models.CharField(blank=True, choices=[('A', 'Categoria A'), ('B', 'Categoria B'), ('C', 'Categoria C'), ('D', 'Categoria D'), ('E', 'Categoria E'), ('AB', 'Categoria AB')], help_text='Categoria habilitada do motorista', max_length=5, null=True, verbose_name='Categoria da CNH'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da CNH'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='CNH'),
        ),
        migrations.AlterField(
            model_name='historicaldriver',
            name='license_category',
            field=models.CharField(blank=True, choices=[('A', 'Categoria A'), ('B', 'Categoria B'), ('C', 'Categoria C'), ('D', 'Categoria D'), ('E', 'Categoria E'), ('AB', 'Categoria AB')], help_text='Categoria habilitada do motorista', max_length=5, null=True, verbose_name='Categoria da CNH'),
        ),
        migrations.AlterField(
            model_name='historicaldriver',
            name='license_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da CNH'),
        ),
        migrations.AlterField(
            model_name='historicaldriver',
            name='license_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='CNH'),
        ),
    ]
