# Generated by Django 5.2 on 2025-06-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0013_remove_historicalloadplan_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalroute',
            name='distance_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Distância (km)'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='geojson',
            field=models.JSONField(blank=True, null=True, verbose_name='GeoJSON'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='points',
            field=models.JSONField(blank=True, null=True, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='stops',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Paradas'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='time_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Tempo (minutos)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Distância (km)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='geojson',
            field=models.JSONField(blank=True, null=True, verbose_name='GeoJSON'),
        ),
        migrations.AlterField(
            model_name='route',
            name='points',
            field=models.JSONField(blank=True, null=True, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stops',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Paradas'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Tempo (minutos)'),
        ),
    ]
