# Generated by Django 5.2 on 2025-06-01 16:07

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0014_alter_historicalroute_distance_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLoadPlan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nome do Plano')),
                ('planned_date', models.DateField(blank=True, db_index=True, editable=False, verbose_name='Data Planejada')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Horário de Saída')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('planned', 'Planejado'), ('loading', 'Carregando'), ('departed', 'Saiu para Entrega'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('max_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Capacidade Peso (kg)')),
                ('max_volume_m3', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Capacidade Volume (m³)')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmsapp.route', verbose_name='Rota')),
                ('vehicle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmsapp.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'historical Plano de Carga',
                'verbose_name_plural': 'historical Planos de Carga',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRouteCompositionDelivery',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='Sequência')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('delivery', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmsapp.delivery')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('load_plan', models.ForeignKey(blank=True, db_constraint=False, help_text='Plano de carga ao qual este pedido pertence. Null para pedidos fora de carga.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmsapp.loadplan', verbose_name='Plano de Carga')),
                ('route_composition', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmsapp.routecomposition')),
            ],
            options={
                'verbose_name': 'historical Entrega da Composição de Rota',
                'verbose_name_plural': 'historical Entregas da Composição de Rota',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
