# Generated by Django 5.2 on 2025-05-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0014_alter_driver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_category',
            field=models.CharField(blank=True, choices=[('Categoria A', 'Categoria A'), ('Categoria B', 'Categoria B'), ('Categoria C', 'Categoria C'), ('Categoria D', 'Categoria D'), ('Categoria E', 'Categoria E'), ('Categoria AB', 'Categoria AB')], help_text='Categoria habilitada do motorista', max_length=30, null=True, verbose_name='Categoria da CNH'),
        ),
        migrations.AlterField(
            model_name='historicaldriver',
            name='license_category',
            field=models.CharField(blank=True, choices=[('Categoria A', 'Categoria A'), ('Categoria B', 'Categoria B'), ('Categoria C', 'Categoria C'), ('Categoria D', 'Categoria D'), ('Categoria E', 'Categoria E'), ('Categoria AB', 'Categoria AB')], help_text='Categoria habilitada do motorista', max_length=30, null=True, verbose_name='Categoria da CNH'),
        ),
    ]
