# Generated by Django 5.2 on 2025-06-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0015_historicalloadplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_load', 'Alocado'), ('picked', 'Separado'), ('loaded', 'Carregado'), ('in_transit', 'Em Trânsito'), ('delivered', 'Entregue'), ('failed', 'Falha na Entrega'), ('cancelled', 'Cancelado')], db_index=True, default='pending', help_text='Situação atual da entrega', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicaldelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_load', 'Alocado'), ('picked', 'Separado'), ('loaded', 'Carregado'), ('in_transit', 'Em Trânsito'), ('delivered', 'Entregue'), ('failed', 'Falha na Entrega'), ('cancelled', 'Cancelado')], db_index=True, default='pending', help_text='Situação atual da entrega', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalloadplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('route_started', 'Roteiro Iniciado'), ('vehicle_assigned', 'Veículo Atribuído'), ('awaiting_loading', 'Aguardando Carregamento'), ('loading', 'Em Carregamento'), ('loaded', 'Carregado'), ('in_transit', 'Em Trânsito'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalroutecomposition',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('planned', 'Planejada'), ('awaiting_loading', 'Aguardando Carregamento'), ('loading', 'Em Carregamento'), ('in_transit', 'Em Trânsito'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], db_index=True, default='draft', help_text='Situação atual da roterização', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='loadplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('route_started', 'Roteiro Iniciado'), ('vehicle_assigned', 'Veículo Atribuído'), ('awaiting_loading', 'Aguardando Carregamento'), ('loading', 'Em Carregamento'), ('loaded', 'Carregado'), ('in_transit', 'Em Trânsito'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='routecomposition',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('planned', 'Planejada'), ('awaiting_loading', 'Aguardando Carregamento'), ('loading', 'Em Carregamento'), ('in_transit', 'Em Trânsito'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], db_index=True, default='draft', help_text='Situação atual da roterização', max_length=30, verbose_name='Status'),
        ),
    ]
