# Generated by Django 5.2 on 2025-05-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0015_alter_driver_license_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('driving-car', 'Carro'), ('driving-hgv', 'Caminhão/Veículo pesado')], default='driving-car', max_length=20, verbose_name='Tipo de Veículo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('driving-car', 'Carro'), ('driving-hgv', 'Caminhão/Veículo pesado')], default='driving-car', max_length=20, verbose_name='Tipo de Veículo'),
        ),
    ]
