# Generated by Django 5.2 on 2025-06-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0016_alter_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routecomposition',
            name='load_plans_direct',
            field=models.ManyToManyField(blank=True, related_name='compositions_direct', to='tmsapp.loadplan', verbose_name='Planos de Carga (direto)'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_script', 'Em Roteiro'), ('in_load', 'Alocado'), ('picked', 'Separado'), ('loaded', 'Carregado'), ('in_transit', 'Em Trânsito'), ('delivered', 'Entregue'), ('failed', 'Falha na Entrega'), ('cancelled', 'Cancelado')], db_index=True, default='pending', help_text='Situação atual da entrega', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicaldelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_script', 'Em Roteiro'), ('in_load', 'Alocado'), ('picked', 'Separado'), ('loaded', 'Carregado'), ('in_transit', 'Em Trânsito'), ('delivered', 'Entregue'), ('failed', 'Falha na Entrega'), ('cancelled', 'Cancelado')], db_index=True, default='pending', help_text='Situação atual da entrega', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalloadplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('route_started', 'Roteiro Iniciado'), ('awaiting_loading', 'Aguardando Carregamento'), ('loading', 'Em Carregamento'), ('loaded', 'Carregado'), ('in_transit', 'Em Trânsito'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='loadplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('route_started', 'Roteiro Iniciado'), ('awaiting_loading', 'Aguardando Carregamento'), ('loading', 'Em Carregamento'), ('loaded', 'Carregado'), ('in_transit', 'Em Trânsito'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=50, verbose_name='Status'),
        ),
    ]
