# Generated by Django 5.2 on 2025-05-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0016_historicalvehicle_vehicle_type_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='historicalcarrier',
            name='representative',
        ),
    ]
