# Generated by Django 5.2 on 2025-06-02 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0017_routecomposition_load_plans_direct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalroutecompositiondelivery',
            name='route_area',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Area de rota ao qual este pedido pertence. Null para pedidos fora de rota.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmsapp.routearea'),
        ),
        migrations.AddField(
            model_name='routecompositiondelivery',
            name='route_area',
            field=models.ForeignKey(blank=True, help_text='Area de rota ao qual este pedido pertence. Null para pedidos fora de rota.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmsapp.routearea'),
        ),
    ]
