# Generated by Django 5.2 on 2025-05-14 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0017_remove_carrier_representative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='carrier',
            name='tmsapp_carr_contact_ddced1_idx',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='historicalcarrier',
            name='contact_name',
        ),
        migrations.AddField(
            model_name='carrier',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='historicalcarrier',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='historicalcarrier',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='historicalcarrier',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='historicalcarrier',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='historicalcarrier',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='historicalcarrier',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Endereço Completo'),
        ),
        migrations.AlterField(
            model_name='historicalcarrier',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Endereço Completo'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['description'], name='tmsapp_carr_descrip_2ee3f6_idx'),
        ),
    ]
