# Generated by Django 5.2 on 2025-05-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0018_remove_carrier_tmsapp_carr_contact_ddced1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='des_address',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='historicalcarrier',
            name='des_address',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Endereço'),
        ),
    ]
