# Generated by Django 5.2 on 2025-06-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0018_historicalroutecompositiondelivery_route_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalroutecompositiondelivery',
            old_name='route_area',
            new_name='route_areas',
        ),
        migrations.RenameField(
            model_name='routecompositiondelivery',
            old_name='route_area',
            new_name='route_areas',
        ),
    ]
