# Generated by Django 5.2 on 2025-05-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0019_carrier_des_address_historicalcarrier_des_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='historicalcarrier',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='CNPJ'),
        ),
    ]
