# Generated by Django 5.2 on 2025-05-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0020_carrier_cnpj_historicalcarrier_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalroutearea',
            name='color_name',
        ),
        migrations.RemoveField(
            model_name='routearea',
            name='color_name',
        ),
        migrations.AddField(
            model_name='historicalroutearea',
            name='hex_color',
            field=models.CharField(default='#0074D9', help_text='Código de cor hexadecimal, ex: #FF0000', max_length=7, verbose_name='Cor HEX'),
        ),
        migrations.AddField(
            model_name='routearea',
            name='hex_color',
            field=models.CharField(default='#0074D9', help_text='Código de cor hexadecimal, ex: #FF0000', max_length=7, verbose_name='Cor HEX'),
        ),
        migrations.AddField(
            model_name='routearea',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='route_areas', to='tmsapp.vehicle', verbose_name='Veículos'),
        ),
    ]
