# Generated by Django 5.2 on 2025-06-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0020_rename_route_areas_historicalroutecompositiondelivery_route_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalroutecomposition',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data Fim'),
        ),
        migrations.AddField(
            model_name='historicalroutecomposition',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data Início'),
        ),
        migrations.AddField(
            model_name='routecomposition',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data Fim'),
        ),
        migrations.AddField(
            model_name='routecomposition',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data Início'),
        ),
    ]
