# Generated by Django 5.2 on 2025-06-02 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0021_historicalroutecomposition_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadplan',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tmsapp.route', verbose_name='Rota'),
        ),
    ]
