# Generated by Django 5.2 on 2025-05-18 13:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0021_remove_historicalroutearea_color_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='route_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='tmsapp.routearea', verbose_name='Área de Rota'),
        ),
        migrations.AddField(
            model_name='historicaldriver',
            name='route_area',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmsapp.routearea', verbose_name='Área de Rota'),
        ),
        migrations.AlterField(
            model_name='historicalload',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Carregamento'),
        ),
        migrations.AlterField(
            model_name='load',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Carregamento'),
        ),
    ]
