# Generated by Django 5.2 on 2025-05-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0022_driver_route_area_historicaldriver_route_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routearea',
            name='vehicles',
        ),
    ]
