# Generated by Django 5.2 on 2025-06-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0022_alter_loadplan_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylocation',
            name='type',
            field=models.CharField(choices=[('warehouse', 'Armazém'), ('store', 'Loja'), ('distribution_center', 'Centro de Distribuição'), ('hub', 'Hub'), ('secondary_warehouse', 'Armazém Secundário'), ('other', 'Outro')], db_index=True, default='other', max_length=30, verbose_name='Tipo de Local'),
        ),
        migrations.AlterField(
            model_name='historicalcompanylocation',
            name='type',
            field=models.CharField(choices=[('warehouse', 'Armazém'), ('store', 'Loja'), ('distribution_center', 'Centro de Distribuição'), ('hub', 'Hub'), ('secondary_warehouse', 'Armazém Secundário'), ('other', 'Outro')], db_index=True, default='other', max_length=30, verbose_name='Tipo de Local'),
        ),
    ]
