# Generated by Django 5.2 on 2025-06-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0023_alter_companylocation_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companylocation',
            old_name='zip_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='historicalcompanylocation',
            old_name='zip_code',
            new_name='postal_code',
        ),
    ]
