# Generated by Django 5.2 on 2025-05-18 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0023_remove_routearea_vehicles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='route_area',
        ),
        migrations.RemoveField(
            model_name='historicaldriver',
            name='route_area',
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='route_area',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmsapp.routearea', verbose_name='Área de Rota'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='route_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='tmsapp.routearea', verbose_name='Área de Rota'),
        ),
    ]
