# Generated by Django 5.2 on 2025-05-18 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0024_remove_driver_route_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='route_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='tmsapp.routearea', verbose_name='Área de Rota'),
        ),
    ]
