# Generated by Django 5.2 on 2025-07-10 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0024_rename_zip_code_companylocation_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='date_delivery',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Entrega'),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='date_delivery',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Entrega'),
        ),
    ]
