# Generated by Django 5.2 on 2025-05-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0025_alter_vehicle_route_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('scheduled', 'Agendada'), ('in_transit', 'Em Trânsito'), ('delivered', 'Entregue'), ('failed', 'Falha na Entrega'), ('cancelled', 'Cancelada')], db_index=True, default='pending', help_text='Situação atual da entrega no fluxo TMS', max_length=15, verbose_name='Status da Entrega'),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('scheduled', 'Agendada'), ('in_transit', 'Em Trânsito'), ('delivered', 'Entregue'), ('failed', 'Falha na Entrega'), ('cancelled', 'Cancelada')], db_index=True, default='pending', help_text='Situação atual da entrega no fluxo TMS', max_length=15, verbose_name='Status da Entrega'),
        ),
    ]
