# Generated by Django 5.2 on 2025-05-20 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
        ('tmsapp', '0027_alter_delivery_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='is_check',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='historicaldelivery',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='historicaldelivery',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='historicaldelivery',
            name='is_check',
        ),
        migrations.RemoveField(
            model_name='historicaldelivery',
            name='phone',
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='crmapp.customer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crmapp.customer', verbose_name='Cliente'),
        ),
    ]
