# Generated by Django 5.2 on 2025-05-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0029_carrier_is_active_delivery_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='des_address',
        ),
        migrations.RemoveField(
            model_name='historicalcarrier',
            name='des_address',
        ),
        migrations.AlterField(
            model_name='carrier',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='historicalcarrier',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Endereço'),
        ),
    ]
