# Generated by Django 5.2 on 2025-05-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0030_remove_carrier_des_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrier',
            old_name='zip_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='historicalcarrier',
            old_name='zip_code',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='historicalcarrier',
            name='address',
        ),
        migrations.AddField(
            model_name='carrier',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='historicalcarrier',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
    ]
