# Generated by Django 5.2 on 2025-05-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0031_rename_zip_code_carrier_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'pendente'), ('scheduled', 'agendada'), ('in-transit', 'em Trânsito'), ('delivered', 'entregue'), ('failed', 'falha na Entrega'), ('cancelled', 'cancelada')], db_index=True, default='pending', help_text='Situação atual da entrega', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicaldelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'pendente'), ('scheduled', 'agendada'), ('in-transit', 'em Trânsito'), ('delivered', 'entregue'), ('failed', 'falha na Entrega'), ('cancelled', 'cancelada')], db_index=True, default='pending', help_text='Situação atual da entrega', max_length=15, verbose_name='Status'),
        ),
    ]
