# Generated by Django 5.2 on 2025-05-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0032_alter_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='filial',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='filial',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Filial'),
        ),
    ]
