# Generated by Django 5.2 on 2025-07-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='link_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
