# Generated by Django 5.2 on 2025-05-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='porcent',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
