# Generated by Django 5.2 on 2025-05-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='porcent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
