# Generated by Django 5.2 on 2025-07-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonotify', '0002_notification_action_notification_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('STARTED', 'Iniciada'), ('PROGRESS', 'Processando'), ('SUCCESS', 'Concluída'), ('FAILURE', 'Falha')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
