# Generated by Django 5.2 on 2025-05-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonotify', '0002_taskrecord_porcent'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
