# Generated by Django 5.2 on 2025-05-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonotify', '0003_taskrecord_id_alter_taskrecord_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='porcent',
            field=models.IntegerField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
